[package]
name = "fastrequest"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
pretty_env_logger = "0.5.0"
rocket = { version = "0.5.1", features = ["json", "tls"] }
serde = "1.0.203"
serde_derive = "1.0.203"
toml = "0.8.14"
