# NOTE: paths starting with '.' are relative to the source directory

[settings]
secrets_file = "./secrets/credentials.toml"
use_env_secrets = false
port = 4433
url = "https://[::]:4433"

[ssl]
cert = "./secrets/cert.pem"
key = "./secrets/key.pem"

# database credentials in secrets
[db]
# TODO: mongodb support?
# one of "mysql" (covers MariaDB), "postgres", "sqlite"
# if sqlite, set username, address, port to blank values,
# and set the database to the file path (not relative!)
dbms = "mysql"
username = "fastrequest"
database = "fastrequest_dev"
address = "127.0.0.1"
port = 3306
