# NOTE: paths starting with '.' are relative to the source directory

[settings]
secrets_file = "./secrets/credentials.toml"
use_env_secrets = false
port = 4433
url = "https://[::]:4433"

[ssl]
cert = "./secrets/cert.pem"
key = "./secrets/key.pem"

# database credentials in secrets
[db]
# TODO: mongddodb support?
# one of "mysql" (covers MariaDB), "postgresql", "sqlite"
dbms = "mysql"
username = "fastrequest"
database = "fastrequest_dev"
address = "10.2.0.3"
port = 3306
